//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XVLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XVLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGDj6Um17oiCd2cCkH4T.
        /// </summary>
        internal static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00DDDDDD.
        /// </summary>
        internal static string ButtonBG {
            get {
                return ResourceManager.GetString("ButtonBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF406380.
        /// </summary>
        internal static string ButtonBorder {
            get {
                return ResourceManager.GetString("ButtonBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF062640.
        /// </summary>
        internal static string ButtonSelectedBG {
            get {
                return ResourceManager.GetString("ButtonSelectedBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF1B86FF.
        /// </summary>
        internal static string ButtonSelectedBorder {
            get {
                return ResourceManager.GetString("ButtonSelectedBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.exe.
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InstallDirectory {
            get {
                return ResourceManager.GetString("InstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.
        /// </summary>
        internal static string LauncherVersion {
            get {
                return ResourceManager.GetString("LauncherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestApp.
        /// </summary>
        internal static string SaveDirectory {
            get {
                return ResourceManager.GetString("SaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gitlab.com/thatonekriegerwriter/Pokemon-Survival-Island-v19/-/raw/{0}/.
        /// </summary>
        internal static string UpdateUrl {
            get {
                return ResourceManager.GetString("UpdateUrl", resourceCulture);
            }
        }
    }
}
